port = "18080"
blog_port="19080"
domain = "127.0.0.1"
group = "blog"

[server]
    [server.ds_config]
        [server.ds_config.redis]
        host = "127.0.0.1"
        port = 26379
        username = ""
        password = "1433223"
    [server.jwt]
    secret = "blog"
    expire = 3600
    [server.console_jwt]
    secret = "console"
    expire = 3600
[blog_user]
    email = "duaaron519@gmail.com"
    password = "1433223qQ"
[admin]
    username = "aaron"
    password = "1433223qQ"
[s3]
    bucket = "media-storage"
    endpoint = "http://127.0.0.1:29000"
    access_key = "admin"
    secret_key = "admin@123"
    region = "cn-north"